name: friendly-time
version: '0.4.1'
synopsis: Print time information in friendly ways
description: Please see README.md
category: Web, Yesod
author: Pat Brisbin <pbrisbin@gmail.com>
maintainer: Pat Brisbin <pbrisbin@gmail.com>
copyright: 2018 Pat Brisbin
license: BSD3
github: pbrisbin/friendly-time

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - base >=4 && <5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - time >=1.5

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - friendly-time
      - hspec
      - time
